# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scmd < Formula
  desc "AI-powered slash commands for any terminal. Works offline by default."
  homepage "https://github.com/sunboy/scmd"
  version "0.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/sunboy/scmd/releases/download/v0.2.0/scmd_0.2.0_macOS_all_brew.tar.gz"
    sha256 "890630c871123bf9d5a88f7d1962d83366c270828ef9380e09627f71bcd2367d"

    def install
      bin.install "scmd"
      # Install bundled llama-server
      libexec.install "libexec/llama-server"
      # Shell completions
      bash_completion.install "completions/scmd.bash" => "scmd"
      zsh_completion.install "completions/scmd.zsh" => "_scmd"
      fish_completion.install "completions/scmd.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunboy/scmd/releases/download/v0.2.0/scmd_0.2.0_linux_amd64_brew.tar.gz"
      sha256 "df2bf9a9b6d6badbe22af193b82ad8e0fb9b9b61703884fd1daf424c14e3b99a"
      def install
        bin.install "scmd"
        # Install bundled llama-server
        libexec.install "libexec/llama-server"
        # Shell completions
        bash_completion.install "completions/scmd.bash" => "scmd"
        zsh_completion.install "completions/scmd.zsh" => "_scmd"
        fish_completion.install "completions/scmd.fish"
      end
    end
  end

  test do
    system "#{bin}/scmd", "--version"
  end
end
