# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scmd < Formula
  desc "AI-powered slash commands for any terminal. Works offline by default."
  homepage "https://github.com/sunboy/scmd"
  version "0.3.0"
  license "MIT"

  on_macos do
    url "https://github.com/sunboy/scmd/releases/download/v0.3.0/scmd_0.3.0_macOS_all_brew.tar.gz"
    sha256 "097e71043ba874081e384dda4b37b4f3097583230cc8dae242a10f5d72ea6750"

    def install
      bin.install "scmd"
      # Install bundled llama-server
      libexec.install "libexec/llama-server"
      # Shell completions
      bash_completion.install "completions/scmd.bash" => "scmd"
      zsh_completion.install "completions/scmd.zsh" => "_scmd"
      fish_completion.install "completions/scmd.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunboy/scmd/releases/download/v0.3.0/scmd_0.3.0_linux_amd64_brew.tar.gz"
      sha256 "d9e8a18681389444f5027a9471e35373aa6f3a5be37d19b7112e46bc553595da"
      def install
        bin.install "scmd"
        # Install bundled llama-server
        libexec.install "libexec/llama-server"
        # Shell completions
        bash_completion.install "completions/scmd.bash" => "scmd"
        zsh_completion.install "completions/scmd.zsh" => "_scmd"
        fish_completion.install "completions/scmd.fish"
      end
    end
  end

  test do
    system "#{bin}/scmd", "--version"
  end
end
