# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scmd < Formula
  desc "AI-powered slash commands for any terminal. Works offline by default."
  homepage "https://github.com/sunboy/scmd"
  version "0.4.2"
  license "MIT"

  on_macos do
    url "https://github.com/sunboy/scmd/releases/download/v0.4.2/scmd_0.4.2_macOS_all_brew.tar.gz"
    sha256 "d0849a45b3f4f528a96133b14e5e4c4d4608a40cb39e1287cb13d607a26a000a"

    def install
      bin.install "scmd"
      # Install bundled llama-server
      libexec.install "libexec/llama-server"
      # Shell completions
      bash_completion.install "completions/scmd.bash" => "scmd"
      zsh_completion.install "completions/scmd.zsh" => "_scmd"
      fish_completion.install "completions/scmd.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sunboy/scmd/releases/download/v0.4.2/scmd_0.4.2_linux_amd64_brew.tar.gz"
      sha256 "72b08e88aa8f49c869af3c642bb3063bee223c91e2e349055564ac897a041004"
      def install
        bin.install "scmd"
        # Install bundled llama-server
        libexec.install "libexec/llama-server"
        # Shell completions
        bash_completion.install "completions/scmd.bash" => "scmd"
        zsh_completion.install "completions/scmd.zsh" => "_scmd"
        fish_completion.install "completions/scmd.fish"
      end
    end
  end

  test do
    system "#{bin}/scmd", "--version"
  end
end
